apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanidm-backup
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
